---
name: on_hello_event1
pack: <%= pack.ref %>
description: Sample rule firing on <%= pack.ref %>.event1.
enabled: true
trigger:
    type: <%= pack.ref %>.event1
action:
    ref: <%= pack.ref %>.greet
    parameters:
        greeting: Yo
